@startuml
node low_latency_apps
queue write_queue
node BlockSci

frame feed_handlers {
    agent sentimentaggregator
    agent marketcollector
}

database DB {
  folder market_data {
    card orderbook
    card volume
    card tick
    card OHLC
  }
  folder "Sentiment Data" {
    card sentiment_index
  }
}

agent webcrawler
frame sentiment {
    node other {
        card trollboxes
        card github
    }
    node social {
        card twitter
        card reddit
    }
    trollboxes --> webcrawler
    github --> webcrawler
    twitter --> webcrawler
    reddit --> webcrawler
}
webcrawler --> sentimentaggregator
sentimentaggregator --> write_queue


frame exchanges {
  card Bitstamp
  card Binance
  card Bittrex
  card Kraken
  card Poloniex
  card GDAX
}
exchanges ---> marketcollector
marketcollector ----> write_queue
write_queue --> DB
marketcollector ---> low_latency_apps
low_latency_apps <--> DB
low_latency_apps --> exchanges


frame full_nodes {
    node BTC
    node ETH
    node LTC
    node BCH

    BTC --> BlockSci
    LTC --> BlockSci
    ETH --> BlockSci
    BCH --> BlockSci
}
BlockSci ---right-> DB




@enduml